### PR TITLE
Added a handle to set a routing via CSP address for KISS

### PR DESCRIPTION
**Pull request by dataGomSpace**
This is necessary to enable routing CSP packets received by the ZMQbridge on the KISS interface.

### CODE REVIEW

**Review by bfol — COMMENTED** [review]
We should avoid making GomSpace specific changes in libcsp unless it is really needed, since it has a high risk of removing compatibility with non GomSpace components and also makes it harder to update libcsp in the future. 
I Will need some background on the purpose and how to use this change before I can perform the review.

**Comment by johandc** [comment]
Why do you need a via address on the kiss interface? Kiss is point to point anyways.

**Comment by dataGomSpace** [comment]
We need to be able to route all packets coming from Kiss to an encryption gateway for decryption.
So for instance:
SAT<->RF<->GND_RADIO<->KISS<->ZMQPROXY<->GATEWAY<->CSP_NODE

**Comment by johandc** [comment]
Okay. Why don't you encapsulate the packet and use the correct address on the radio of the satellite before it leaves the sat?

We use a small interface called if_tun (for secure tunnels) between the satellite and the mission control. So the radio rf, and ground segment is considered an insecure place. Just like VPN / IPsec.

Putting the responsibility of this into the bridge is the wrong place in my opinion. Also the solution of matching interface sting names is not very elegant.

I can share csp_if_tun with you, one moment.

**Comment by johandc** [comment]
Here's our solution:

https://github.com/libcsp/libcsp/commit/70e43adec06dea20dc2c484ca37fb66254f83267

Including a bit of documentation.

**Comment by dataGomSpace** [comment]
Thanks Johan. That is a more elegant solution to the problem.
But, combined with our encryption,  I'm afraid it adds to much overhead for us on the RF link.
But we might be able to do something similar, but only on the ground.

**Comment by johandc** [comment]
Okay. What frame size / MTU do you have? Internally, and on the RF?
CSP CAN 2.0 takes 2026 bytes packets, but if the problem is with the RF link there's not much to do.

**Comment by dataGomSpace** [comment]
The problem is the MTU on the RF link. It doesn't allow much overhead on the CSP packets.

**Comment by dataGomSpace** [comment]
Actually it doesn't put us over the top on the MTU on the RF link. 
So we can use this approach and avoid any Gomspace changes in libcsp.
Thanks @johandc

**Pull request closed without merging**
